[supabase]
url = "https://mcgqfpncstmbvwdmsxnl.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZ3FmcG5jc3RtYnZ3ZG1zeG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1OTc2NjEsImV4cCI6MjA1MDE3MzY2MX0.6AHurJQCyfw_sdu3Kg05fDyxxBo9wwEZKmTbfCw3kXs"